site:
  title: "OMM"
  description: "Olimpiada Michoacana de Matemáticas"
  based: "Morelia"
  timezone: "America/Mexico_City"
  locale: "es-MX"
  nav:
    - label: "Acerca"
      href: "/acerca"
    - label: "Noticias"
      href: "/blog"
    - label: "Prepárate"
      href: "/recursos"
    - label: "Acceder"
      href: "https://registro.olimpiadamatematicasmichoacan.org:8443/login/index.php"