site:
  title: "OMM"
  description: "Olimpiada Michoacana de Matem√°ticas"
  based: "Morelia"
  timezone: "America/Mexico_City"
  locale: "es-MX"
  nav:
    - label: "Noticias"
      href: "/blog"
    - label: "Acerca"
      href: "/about"
    - label: "Proyectos"
      href: "/projects"