site:
  title: "OMM"
  description: "Olimpiada Michoacana de Matem√°ticas"
  based: "Morelia"
  timezone: "America/Mexico_City"
  locale: "es-MX"
  nav:
    - label: "Acerca"
      href: "/about"
    - label: "Noticias"
      href: "/blog"
    - label: "Recursos"
      href: "/projects"
    - label: "Acceder"
      href: "https://registro.olimpiadamatematicasmichoacan.org:8443/login/index.php"